
[functions.ai-assistant]
enabled = true
verify_jwt = true
import_map = "./functions/ai-assistant/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-assistant/index_v2.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-assistant/*.html" ]
